-- MySQL Script generated by MySQL Workbench
-- seg 27 jan 2020 17:38:29 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`aplicacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aplicacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aplicacao` (
  `id` INT NOT NULL,
  `nome_app` VARCHAR(45) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL,
  `data_alteracao` TIMESTAMP NOT NULL,
  `usuario_criacao` VARCHAR(45) NOT NULL,
  `usuario_alteracao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));

CREATE UNIQUE INDEX `nome_app_UNIQUE` ON `mydb`.`aplicacao` (`nome_app` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`cluster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cluster` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cluster` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpu_porcentagem` INT NOT NULL,
  `total_core` INT NOT NULL,
  `espaco_disco_utilizado` VARCHAR(45) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL,
  `data_alteracao` TIMESTAMP NOT NULL,
  `usuario_criacao` VARCHAR(45) NOT NULL,
  `usuario_alteracao` VARCHAR(45) NOT NULL,
  `vcenter_id` INT NOT NULL,
  PRIMARY KEY (`id`, `vcenter_id`),
  CONSTRAINT `fk_cluster_vcenter1`
    FOREIGN KEY (`vcenter_id`)
    REFERENCES `mydb`.`vcenter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cluster_vcenter1_idx` ON `mydb`.`cluster` (`vcenter_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`host`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`host` ;

CREATE TABLE IF NOT EXISTS `mydb`.`host` (
  `id` INT NOT NULL,
  `nome_vm` VARCHAR(45) NOT NULL,
  `total_core` INT NOT NULL,
  `total_memoria` INT NOT NULL,
  `total_espaco_disco` INT NOT NULL,
  `workload_procentagem` INT NOT NULL,
  `workload_cores` INT NOT NULL,
  `workload_memoria` INT NOT NULL,
  `workload_disco` INT NOT NULL,
  `nome_so` VARCHAR(45) NOT NULL,
  `versao_so` VARCHAR(45) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL,
  `data_alteracao` TIMESTAMP NOT NULL,
  `usuario_criacao` VARCHAR(45) NOT NULL,
  `usuario_alteracao` VARCHAR(45) NOT NULL,
  `cluster_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cluster_id`),
  CONSTRAINT `fk_host_cluster1`
    FOREIGN KEY (`cluster_id`)
    REFERENCES `mydb`.`cluster` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idvm_UNIQUE` ON `mydb`.`host` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `nome_vm_UNIQUE` ON `mydb`.`host` (`nome_vm` ASC) VISIBLE;

CREATE UNIQUE INDEX `total_vcpu_UNIQUE` ON `mydb`.`host` (`total_core` ASC) VISIBLE;

CREATE INDEX `fk_host_cluster1_idx` ON `mydb`.`host` (`cluster_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`vcenter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vcenter` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vcenter` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL,
  `data_alteracao` TIMESTAMP NOT NULL,
  `usuario_criacao` VARCHAR(45) NOT NULL,
  `usuario_alteracao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vm` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vm` (
  `idv` INT NOT NULL,
  `nome_vm` VARCHAR(45) NOT NULL,
  `total_vcpu` INT NOT NULL,
  `total_memoria` INT NOT NULL,
  `total_espaco_disco` INT NOT NULL,
  `workload_procentagem` INT NOT NULL,
  `workload_cores` INT NOT NULL,
  `workload_memoria` INT NOT NULL,
  `workload_disco` INT NOT NULL,
  `nome_so` VARCHAR(45) NOT NULL,
  `versao_so` VARCHAR(45) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL,
  `data_alteracao` TIMESTAMP NOT NULL,
  `usuario_criacao` VARCHAR(45) NOT NULL,
  `usuario_alteracao` VARCHAR(45) NOT NULL,
  `aplicacao_id` INT NOT NULL,
  `host_id` INT NOT NULL,
  PRIMARY KEY (`idv`, `aplicacao_id`, `host_id`),
  CONSTRAINT `fk_vm_aplicacao`
    FOREIGN KEY (`aplicacao_id`)
    REFERENCES `mydb`.`aplicacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vm_host1`
    FOREIGN KEY (`host_id`)
    REFERENCES `mydb`.`host` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idvm_UNIQUE` ON `mydb`.`vm` (`idv` ASC) VISIBLE;

CREATE UNIQUE INDEX `nome_vm_UNIQUE` ON `mydb`.`vm` (`nome_vm` ASC) VISIBLE;

CREATE UNIQUE INDEX `total_vcpu_UNIQUE` ON `mydb`.`vm` (`total_vcpu` ASC) VISIBLE;

CREATE INDEX `fk_vm_aplicacao_idx` ON `mydb`.`vm` (`aplicacao_id` ASC) VISIBLE;

CREATE INDEX `fk_vm_host1_idx` ON `mydb`.`vm` (`host_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
